Token schema, endpoint for create and read token
ubclaunchpad/localization pull request #2
Opened 2024-10-11 21:52 UTC by angelafeliciaa

2024-10-12 21:16 UTC, angelafeliciaa commented
<img width="680" alt="Screenshot 2024-10-12 at 14 14 48" src="https://github.com/user-attachments/assets/41109b13-3e4f-4237-8d22-d7f0f1f58259">
<img width="684" alt="Screenshot 2024-10-12 at 14 15 19" src="https://github.com/user-attachments/assets/39817921-c6ce-4e51-91fd-3df39d0685da">

2024-10-12 21:22 UTC, kevinrczhang requested changes
Great work! Just a minor suggestion + I would like to see some unit tests implemented through. You can see how they're done here:
https://docs.djangoproject.com/en/5.1/topics/testing/overview/

2024-10-12 21:22 UTC, kevinrczhang commented on core/i18nilize/views.py
> +            return Response({'error': 'Token not found.'}, status=status.HTTP_404_NOT_FOUND)
wrap this into one APIVIew called TokenView, 
get and post should be functions underneath the class

2024-10-12 21:40 UTC, kevinrczhang commented
One more thing, we will want to fetch by token value. Fetching by their primary key is insecure. Otherwise, everything else is great!

2024-10-13 00:38 UTC, hriday330 approved these changes
Unit tests look good! Great work - once Kevin has also approved you can merge it

2024-10-13 00:44 UTC, kevinrczhang approved these changes
:shipit:

2024-10-13 01:00 UTC, merged